define([],
    function () {
        return {
            contactAddress: "联系地址：",
            certificateAddress: "证件地址：",
            commonAddress: "常住地址：",
            newAddress: "新增地址：",
            province: "省/直辖市",
            city: "市",
            district: "区/县",
            detailedAddress: "详细地址：",
            postCode: "邮政编码：",
            job: "职业：",
            chooseProvince: "选择省/直辖市",
            chooseCity: "选择市",
            chooseDistrict: "选择区/县",
            chooseJob: "选择职业",
            showCard: "请确认卡片",
            annualFee: "年费：{0}元/年",
            flatFee: "工本费：{0}元。",
            cardCostInfo: "年费：{0}元/年，工本费：{1}元",
            warmPrompt: "温馨提示：",
            warmPrompt1: "温馨提示",
            prompt: "提示",
            signProduct: "请选择签约产品",
            onlineBank: "网上银行",
            mobileBank: "手机银行",
            phoneBank: "电话银行",
            sms: "短信通知",
            opened: "已开通",
            authToolDoesntSupported: "本机内认证工具不支持",
            authToolSoldOut: "认证工具已发完"
        };
    });