define([], function () {
    var pars = {
        specialSymbolWhiteList: [
            { code: "1", text: "." },
            { code: "2", text: "。" },
            { code: "3", text: "！" },
            { code: "4", text: "!" },
            { code: "5", text: " " },
            { code: "6", text: "," },
            { code: "7", text: "，" },
            { code: "8", text: "/" },
            { code: "9", text: "-" },
            { code: "10", text: "~" },
            { code: "11", text: "·" },
            { code: "12", text: "#" },
            { code: "13", text: "￥" },
            { code: "14", text: "$" },
            { code: "15", text: "'" },
            { code: "16", text: "‘" },
            { code: "17", text: '"' },
            { code: "18", text: '“' },
            { code: "19", text: '”' },
            { code: "20", text: '(' },
            { code: "21", text: ')' },
            { code: "22", text: '（' },
            { code: "23", text: '）' },
            { code: "24", text: '=' },
            { code: "25", text: '+' },
            { code: "26", text: '、' },
            { code: "27", text: '<' },
            { code: "28", text: '>' },
            { code: "29", text: '?' },
            { code: "30", text: '？' },
            { code: "31", text: ':' },
            { code: "32", text: '：' },
            { code: "33", text: '；' },
            { code: "34", text: ';' },
            { code: "35", text: '\\' },
            { code: "36", text: '|' },
            { code: "37", text: '{' },
            { code: "38", text: '}' },
            { code: "39", text: '[' },
            { code: "40", text: ']' },
            { code: "41", text: '@' },
            { code: "42", text: '%' },
            { code: "43", text: '……' },
            { code: "44", text: '&' },
            { code: "45", text: '*' },
            { code: "46", text: '——' },
            { code: "47", text: '《' },
            { code: "48", text: '》' },
            { code: "49", text: '^' },
            { code: "50", text: '_' },
        ]
    }
    return pars;
});